# Generated by Django 4.2.1 on 2023-05-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_options_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='posts',
        ),
        migrations.AddField(
            model_name='category',
            name='posts',
            field=models.ManyToManyField(related_name='categories', to='core.post'),
        ),
    ]
