# Generated by Django 4.2.1 on 2023-05-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_post_options_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
